/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.lms;

import java.io.IOException;
import java.io.PrintStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.Scanner;

public class ServerApp {
  public static void main(String[] args) throws UnknownHostException, IOException {
    System.out.println("서버 수업 관리 시스템입니다.");
    try (ServerSocket serverSocket = new ServerSocket(12345)) {
      System.out.println("클라이언트 연결 대기중");
      while (true) {
        Socket socket = serverSocket.accept();
        processRequest(socket);
        System.out.println("--------------------------------------------------");
      }
    } catch (Exception e) {
      System.out.println("서버 준비중 오류 발생");
      e.printStackTrace();
      return;
    }
  }

  public static void processRequest(Socket clientSocket) throws Exception {
    try (Socket socket = clientSocket;
        Scanner in = new Scanner(socket.getInputStream());
        PrintStream out = new PrintStream(socket.getOutputStream())) {
      System.out.println("통신을 위한 입출력 스트림을 준비하였음");
      String message = in.nextLine();
      System.out.println(message);
      out.println("echo message : " + message);
    } catch (Exception e) {
      System.out.println("Exception occurs");
      e.printStackTrace();
    }
  }
}
