/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.lms;

public class ServerApp {
  public static void main(String[] args) {
    System.out.println("서버 수업 관리 시스템입니다.");
  }
}
